Barberland.Web/ViewComponents/WidgetViewComponent.cs
using System;
using System.Reflection.Metadata;
using Barberland.Web.Models;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Barberland.Web.ViewComponents
{
	public class WidgetViewComponent : ViewComponent
	{
		public WidgetViewComponent()
		{
		}

        public IViewComponentResult Invoke(string ViewName)
        {
            object ViewModel;
            if (ViewName == "NavigationBar")
            {
                ViewModel = new NavigationBarViewModel();
            }
            else if (ViewName == "Footer")
            {
                ViewModel = PopulateFooterViewModel();
            }
            else
            {
                ViewModel = new object();
            }
            return View(ViewName, ViewModel);
        }

        private static FooterViewModel PopulateFooterViewModel()
        {
            FooterViewModel ViewModel = new()
            {
                FooterDescription = "Test Footer Description",
                FooterContactMobile = "089123456789",
                FooterContactEmail = "testemail@gmail.com",
                FooterCopyright = "Barberland " + DateTime.Now.Year.ToString(),
                FacebookURL = "https://facebook.com",
                TwitterURL = "https://x.com",
                InstagramURL = "https://instagram.com"
            };

            return ViewModel;
        }
    }
}

Barberland.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Barberland</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/fixed.css" asp-append-version="false">
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="false">

    <!-- jQuery js -->
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="false"></script>
    <!-- Bootstrap js-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="false"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <link rel="stylesheet" href="~/Barberland.Web.styles.css" asp-append-version="true" />

    <!-- Fontawesome icon pack -->
    <script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>
</head>
<body data-spy="scroll" data-target="#navbarResponsive">
    <header>
        @await Component.InvokeAsync("Widget", "NavigationBar")
    </header>

    <div class="content">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    @await Component.InvokeAsync("Widget", "Footer")

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>